---

- name: Add ansible repository
  yum_repository:
    name: ansible
    description: Ansible for EL7
    baseurl: http://releases.ansible.com/ansible/rpm/release/epel-7-$basearch/
    enabled: true
    metadata_expire: 7d
    gpgcheck: false

- name: Install dependencies
  yum:
    state: present
    name:
      - yamllint
      - git
      # The ipaddr filter requires python-netaddr be installed
      - python-netaddr
      # Speeding Up Vault Operations
      # https://docs.ansible.com/ansible/latest/user_guide/vault.html#speeding-up-vault-operations
      - python2-cryptography
      # required for dig lookup (nagios role)
      - python-dns
      - python-pip
  when: not ansible_check_mode

- name: Install python dependencies
  pip:
    name: 
      - Jinja2==2.8
      - ansible==2.8.4
      - ansible-lint==3.5.1
 
- name: Uninstall 
  yum:
    state: absent
    name:
      - python-jinja2
      - ansible
      - ansible-lint
  when: not ansible_check_mode
